# Generated by Django 3.1.1 on 2020-09-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('Category', models.CharField(max_length=100)),
                ('upload', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
