# Generated by Django 3.1.1 on 2020-09-28 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Musician',
            new_name='Product',
        ),
    ]
