# Generated by Django 3.1.1 on 2020-10-03 13:05

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_auto_20201003_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='product_name'),
        ),
    ]
