# Generated by Django 3.1.1 on 2020-10-06 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0008_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='post',
            new_name='product',
        ),
    ]
